// ═══════════════════════════════════════════════════════════════════════════
// ROS STARTUP DATABASE
// Companies featured by the Rational Optimist Society
// Last updated: February 2026
// ═══════════════════════════════════════════════════════════════════════════

const COMPANIES = [
  // ─── DEFENSE & SECURITY ───
  {
    name: "Anduril Industries",
    sector: "Defense & Security",
    description: "Building interoperable sensors and autonomous systems for the battlefield. Products include Roadrunner interceptor, Fury autonomous aircraft, Ghost recon drone, and Lattice OS. Won $642M Marine Corps anti-drone contract and $1.1B Australian Navy Ghost Shark deal.",
    thesis: "Lattice OS is becoming the de facto operating system for autonomous defense. Their vertical integration strategy mirrors early SpaceX — own the stack, own the margin.",
    founder: "Palmer Luckey, Brian Schimpf, Trae Stephens",
    location: "Costa Mesa, CA",
    state: "CA",
    lat: 33.6846,
    lng: -117.8265,
    stage: "Series G",
    founded: 2017,
    fundingStage: "Series G",
    totalRaised: "$2.5B+",
    valuation: "$78B+",
    investors: ["Founders Fund", "a16z", "General Catalyst", "8VC"],
    tags: ["autonomous drones", "AI", "defense", "sensors", "Lattice OS"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/rational-optimist-awards-part-2",
    rosCoverage: "Featured in Rational Optimist Awards"
  },
  {
    name: "Saronic",
    sector: "Defense & Security",
    description: "Autonomous surface vessels built at shipyard scale. Vertically integrated 'shipyard as startup' producing autonomous boats for naval defense on rapid software development cycles.",
    thesis: "Saronic's 'shipyard as startup' model is revolutionary — they're building autonomous naval vessels on software development timelines, not traditional shipbuilding cycles.",
    founder: "Dino Sarti",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Late Stage",
    founded: 2022,
    fundingStage: "Late Stage",
    totalRaised: "$600M+",
    valuation: "$4.0B",
    investors: ["a16z"],
    tags: ["autonomous", "naval", "shipbuilding", "defense"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/spacex-of-the-sea",
    rosCoverage: "Featured article: 'SpaceX of the Sea'"
  },
  {
    name: "Neros",
    sector: "Defense & Security",
    description: "America's leading FPV drone manufacturer. Produces ~1,000 drones monthly. Selected as US Army's primary FPV manufacturer for the Attritable Systems program. Delivered 6,000 Archer drones to Ukraine.",
    thesis: "FPV drones are the new infantry weapon. Neros is scaling American drone manufacturing to meet urgent military demand.",
    founder: "Soren Monroe-Anderson, Olaf Hichwa",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series B",
    founded: 2022,
    fundingStage: "Series B",
    totalRaised: "$110M+",
    valuation: "",
    investors: ["Sequoia Capital"],
    tags: ["FPV drones", "manufacturing", "defense", "Ukraine"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    rosCoverage: "Site visit, Rational Optimist Awards"
  },
  {
    name: "Allen Control Systems",
    sector: "Defense & Security",
    description: "Bullfrog autonomous gun turret achieves ~$10 cost-per-kill against drones. Bolts onto standard military weapons. Demonstrated swarm engagement capabilities at DoD events.",
    thesis: "At $10 per kill vs $100K+ missiles, the economics are transformative for counter-drone warfare.",
    founder: "Steve Simoni",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$42M",
    valuation: "",
    investors: ["Craft Ventures"],
    tags: ["counter-drone", "gun turret", "autonomous", "defense"],
    rosLink: "https://podcasts.apple.com/us/podcast/rational-optimist-podcast",
    rosCoverage: "Podcast interview with founder"
  },
  {
    name: "Flyby Robotics",
    sector: "Defense & Security",
    description: "AI-powered autonomous drone systems. Building 'flying brains' that can operate independently without human pilots using advanced computer vision.",
    thesis: "Autonomous drones need to think for themselves — Flyby is building the AI that makes that possible.",
    founder: "Jason Lu",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    investors: [],
    tags: ["autonomous drones", "AI", "computer vision"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/new-podcast-drones-just-got-scary",
    rosCoverage: "Podcast episode: 'Drones Just Got Scary Smart'"
  },
  {
    name: "Poseidon Systems",
    sector: "Defense & Security",
    description: "Ocean defense and maritime autonomy systems. Modernizing ekranoplan technology for next-generation naval applications.",
    thesis: "Naval warfare is going autonomous — building the underwater and surface systems for the next era of maritime defense.",
    founder: "",
    location: "San Diego, CA",
    state: "CA",
    lat: 32.7200,
    lng: -117.1700,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$12M+",
    valuation: "",
    investors: [],
    tags: ["maritime", "defense", "autonomous systems", "ekranoplan"],
    rosLink: "https://www.rationaloptimistsociety.com",
    rosCoverage: "Featured on ROS website"
  },

  // ─── NUCLEAR ENERGY ───
  {
    name: "Valar Atomics",
    sector: "Nuclear Energy",
    description: "First startup in history to split the atom with its own reactor core. Building gigasites with hundreds of SMRs. Achieved zero-power criticality at Los Alamos. Business model: use nuclear energy to create hydrogen, then bond with CO2 to create clean jet fuel, diesel, gasoline.",
    thesis: "Nuclear-powered synthetic fuels could disrupt the $4T hydrocarbon market while providing clean baseload power.",
    founder: "Isaiah Taylor",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series A",
    founded: 2023,
    fundingStage: "Series A",
    totalRaised: "$149M",
    valuation: "",
    investors: [],
    tags: ["SMR", "nuclear", "synthetic fuels", "HALEU"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-standard-oil-of-nuclear",
    rosCoverage: "Featured article: 'The Standard Oil of Nuclear'"
  },
  {
    name: "Aalo Atomics",
    sector: "Nuclear Energy",
    description: "Pragmatic SMR approach using off-the-shelf fuel and existing supply chains. Building test reactor in Idaho. Selected for DOE Reactor Pilot Program. Targeting July 4, 2026 activation.",
    thesis: "The fastest path to deployed nuclear is using what already exists — Aalo's pragmatism could win the SMR race.",
    founder: "Matt Loszak",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    investors: [],
    tags: ["SMR", "nuclear", "data centers"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-first-nuclear-smr-will-be",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "Radiant",
    sector: "Nuclear Energy",
    description: "Portable 1.2MW nuclear microreactors for austere environments and off-grid use. $300M Series D. Selected for DOE Reactor Pilot Program. 20-reactor Equinix pre-order. Air Force deployment by 2028.",
    thesis: "1.2MW that fits on a truck and powers a forward operating base without fuel convoys — that's a game-changer for military operations.",
    founder: "Doug Bernauer",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series D",
    founded: 2020,
    fundingStage: "Series D",
    totalRaised: "$465M+",
    valuation: "",
    investors: [],
    tags: ["microreactor", "nuclear", "portable", "defense"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-first-nuclear-smr-will-be",
    rosCoverage: "Featured in SMR Power Rankings"
  },
  {
    name: "Kairos Power",
    sector: "Nuclear Energy",
    description: "Building molten salt microreactors for Google. Developing Hermes reactor in Oak Ridge. Targeting mid-2026 activation. Positioned as first civilian SMR deployment.",
    thesis: "Google's backing and Tennessee Valley Authority deal positions Kairos as the frontrunner for first commercial SMR deployment.",
    founder: "Mike Laufer, Edward Blandford",
    location: "Alameda, CA",
    state: "CA",
    lat: 37.7652,
    lng: -122.2416,
    stage: "Late Stage",
    founded: 2016,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "",
    investors: ["Google"],
    tags: ["SMR", "nuclear", "molten salt", "Google"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-first-nuclear-smr-will-be",
    rosCoverage: "Featured in SMR Power Rankings"
  },
  {
    name: "General Matter",
    sector: "Nuclear Energy",
    description: "Rebuilding American uranium enrichment capacity for next-gen nuclear fuels. Founders Fund-incubated. $1.5B enrichment facility in Paducah, KY. $900M DOE HALEU contract.",
    thesis: "No HALEU fuel means no advanced reactors. General Matter is solving the supply chain that everyone else depends on.",
    founder: "Scott Nolan, Lee Robinson",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9170,
    lng: -118.4160,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$50M+",
    valuation: "",
    investors: ["Founders Fund"],
    tags: ["uranium", "enrichment", "nuclear fuel", "HALEU"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-first-nuclear-smr-will-be",
    rosCoverage: "Featured article on nuclear fuel supply"
  },

  // ─── ROBOTICS & MANUFACTURING ───
  {
    name: "Hadrian",
    sector: "Robotics & Manufacturing",
    description: "Software-defined automated factories producing high-precision machined parts for aerospace and defense. $260M Series C. Expanding to 270,000 sq ft Mesa, AZ facility.",
    thesis: "While everyone builds weapons systems, someone has to machine the parts — and US capacity is dangerously thin. Hadrian is solving this bottleneck.",
    founder: "Chris Power",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8358,
    lng: -118.3406,
    stage: "Series C",
    founded: 2020,
    fundingStage: "Series C",
    totalRaised: "$260M+",
    valuation: "$1.6B",
    investors: ["a16z", "Lux Capital", "Founders Fund"],
    tags: ["automated factory", "CNC", "aerospace", "defense"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/how-america-builds-real-things-again",
    rosCoverage: "#1 manufacturing startup pick, site visit"
  },
  {
    name: "Machina Labs",
    sector: "Robotics & Manufacturing",
    description: "Giant robotic arms that automate metal forming. Roboforming technology. Toyota partnership for auto body panels. $35M Abu Dhabi investment. Air Force contract.",
    thesis: "Machina's roboforming tech makes metal shaping as flexible as 3D printing but at production scale.",
    founder: "Ed Mehr",
    location: "Chatsworth, CA",
    state: "CA",
    lat: 34.2572,
    lng: -118.6012,
    stage: "Series B",
    founded: 2019,
    fundingStage: "Series B",
    totalRaised: "$80M+",
    valuation: "",
    investors: ["NVentures", "Innovation Endeavors", "Lockheed Martin Ventures"],
    tags: ["robotic manufacturing", "metal forming", "automotive", "NASA"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/going-robotic",
    rosCoverage: "Featured article: 'Going Robotic'"
  },
  {
    name: "Rangeview",
    sector: "Robotics & Manufacturing",
    description: "Automated 'cyber foundry' using robotics and materials science for investment casting of metal parts. Air Force SBIR for turbine components. Expanded El Segundo facility.",
    thesis: "Investment casting hasn't changed in decades — Rangeview's robotic approach brings software speed to ancient metallurgy.",
    founder: "Cameron Schiller, Aeden Gasser-Brennan",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9185,
    lng: -118.4155,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    investors: [],
    tags: ["casting", "foundry", "robotics", "manufacturing"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/how-america-builds-real-things-again",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "DIRAC",
    sector: "Robotics & Manufacturing",
    description: "The 'anti-software software company' that generates assembly instructions for industrial manufacturers. AI-generated visual guides for the factory floor.",
    thesis: "Bad work instructions cause defects, slowdowns, and training bottlenecks. DIRAC fixes one of manufacturing's most overlooked problems.",
    founder: "Fil Aronshtein",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    investors: [],
    tags: ["manufacturing", "work instructions", "AI", "industrial"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/how-america-builds-real-things-again",
    rosCoverage: "Featured article on manufacturing"
  },
  {
    name: "Bedrock Robotics",
    sector: "Robotics & Manufacturing",
    description: "Retrofits existing heavy construction equipment — excavators, bulldozers, loaders — with reversible hardware and software for fully autonomous operations. Founded by Waymo engineers.",
    thesis: "Why replace a $500K excavator when you can make it autonomous for a fraction of the cost? Targeting an 800,000 worker shortage in construction.",
    founder: "Mory Gharib, Andrew Spiteri",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series B",
    founded: 2023,
    fundingStage: "Series B",
    totalRaised: "$350M+",
    valuation: "$1.75B",
    investors: ["8VC"],
    tags: ["autonomous construction", "heavy equipment", "retrofit autonomy"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/going-robotic",
    rosCoverage: "Featured article on robotics"
  },

  // ─── SPACE & AEROSPACE ───
  {
    name: "Apex Space",
    sector: "Space & Aerospace",
    description: "The 'Foxconn of satellite buses.' Standardized, configurable satellite platforms with transparent pricing. $45.9M Space Force contract. Producing 200+ satellites/year.",
    thesis: "Satellites shouldn't be bespoke — Apex is bringing mass production economics to space hardware.",
    founder: "Ian Cinnamon, Max Benassi",
    location: "Playa Vista, CA",
    state: "CA",
    lat: 33.9745,
    lng: -118.4280,
    stage: "Series D",
    founded: 2022,
    fundingStage: "Series D",
    totalRaised: "$400M+",
    valuation: "$1B+",
    investors: ["a16z", "8VC", "Shield Capital"],
    tags: ["satellite buses", "manufacturing", "space", "Space Force"],
    rosLink: "https://www.rationaloptimistsociety.com/post/the-henry-ford-of-satellites",
    rosCoverage: "Podcast interview, featured article: 'Henry Ford of Satellites'"
  },
  {
    name: "AstroForge",
    sector: "Space & Aerospace",
    description: "Asteroid mining satellites targeting platinum-group metals. Building technology to make space resources commercially viable.",
    thesis: "A single asteroid contains more platinum than has ever been mined on Earth. AstroForge is building the extraction technology.",
    founder: "Matt Gialich, Jose Acain",
    location: "Huntington Beach, CA",
    state: "CA",
    lat: 33.6595,
    lng: -117.9988,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$55M+",
    valuation: "",
    investors: [],
    tags: ["asteroid mining", "platinum", "space resources"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-65-million-cube",
    rosCoverage: "Featured article: 'The $65 Million Cube'"
  },

  // ─── SUPERSONIC & HYPERSONIC ───
  {
    name: "Boom Supersonic",
    sector: "Supersonic & Hypersonic",
    description: "Designing the Overture supersonic commercial jet. XB-1 demonstrator completed test flights. Proprietary Symphony engine. 130+ orders from United and American Airlines.",
    thesis: "Proprietary engines are the unlock — no one else is building a purpose-built supersonic commercial engine.",
    founder: "Blake Scholl, Joe Wilding",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    stage: "Late Stage",
    founded: 2014,
    fundingStage: "Late Stage",
    totalRaised: "$700M+",
    valuation: "$1.5B",
    investors: ["Y Combinator", "Bessemer"],
    tags: ["supersonic", "aviation", "commercial jets", "Symphony engine"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/dude-wheres-my-supersonic-jet",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "Hermeus",
    sector: "Supersonic & Hypersonic",
    description: "Building Mach 5 hypersonic jets with hybrid Chimera engine. Quarterhorse test program with escalating aircraft. First jet flew May 2024. Military applications first.",
    thesis: "DoD will pay for Mach 5 capabilities that commercial aviation won't need for decades. Military-first is the smart path.",
    founder: "AJ Piplica",
    location: "Atlanta, GA",
    state: "GA",
    lat: 33.7490,
    lng: -84.3880,
    stage: "Series C",
    founded: 2018,
    fundingStage: "Series C",
    totalRaised: "$200M+",
    valuation: "",
    investors: ["Khosla Ventures", "Founders Fund"],
    tags: ["hypersonic", "Mach 5", "military", "aviation", "Chimera engine"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/dude-wheres-my-supersonic-jet",
    rosCoverage: "Featured article on supersonic/hypersonic"
  },
  {
    name: "Astro Mechanica",
    sector: "Supersonic & Hypersonic",
    description: "Electric Adaptive Engine for supersonic flight that transitions from turbofan to ramjet. Targeting subsonic to Mach 5 speeds. Also pursuing 3x cheaper space launch.",
    thesis: "A single engine architecture that works from takeoff to Mach 5 could unlock both supersonic flight and affordable space access.",
    founder: "Ian Brooke",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2023,
    fundingStage: "Series A",
    totalRaised: "$27M+",
    valuation: "",
    investors: ["a16z", "Lowercarbon Capital", "United Airlines"],
    tags: ["supersonic", "electric engine", "adaptive", "space launch", "Y Combinator"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/dude-wheres-my-supersonic-jet",
    rosCoverage: "Site visit, featured article"
  },

  // ─── CLIMATE & ENERGY ───
  {
    name: "Terraform Industries",
    sector: "Climate & Energy",
    description: "Modular synthetic fuel production from solar energy and air. Terraformer converts sunlight + CO2 into pipeline-grade methane. Demonstrated 99.4% purity.",
    thesis: "If you can make fuel from sunlight and air, you've solved both energy storage and decarbonization in one stroke.",
    founder: "Casey Handmer",
    location: "Burbank, CA",
    state: "CA",
    lat: 34.1808,
    lng: -118.3090,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$26M",
    valuation: "",
    investors: [],
    tags: ["synthetic fuel", "carbon capture", "solar", "methane"],
    rosLink: "https://podcasts.apple.com/us/podcast/rational-optimist-podcast",
    rosCoverage: "Podcast Episode #44: 'Why He Quit NASA to End The Oil Industry'"
  },
  {
    name: "Rainmaker",
    sector: "Climate & Energy",
    description: "Drone-enabled cloud seeding for water scarcity. Running the largest cloud seeding program in modern US history in Utah. Founded by 23-year-old Augustus Doricko.",
    thesis: "We have the technology to make it rain — Rainmaker is deploying it at scale where water is most needed.",
    founder: "Augustus Doricko",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9188,
    lng: -118.4162,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$25M",
    valuation: "",
    investors: ["Lowercarbon Capital"],
    tags: ["cloud seeding", "weather modification", "water", "drones"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/austin-detroit-winning",
    rosCoverage: "Featured article"
  },

  // ─── BIOTECH & CONSUMER ───
  {
    name: "Atom Bodies",
    sector: "Biotech & Health",
    description: "AI-powered prosthetic arms with 26 degrees of finger freedom. Uses LLMs to interpret nerve signals. Takes just 5 minutes to teach the arm. Restoring dexterity and dignity.",
    thesis: "The convergence of AI and bionics means prosthetics can finally match the complexity of human movement.",
    founder: "Tyler Hayes",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7740,
    lng: -122.4200,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    investors: [],
    tags: ["prosthetics", "AI", "bionics", "LLM"],
    rosLink: "https://x.com/RationalOptSoc",
    rosCoverage: "Site visit, Twitter/X feature"
  },
  {
    name: "Osmo",
    sector: "Consumer Tech",
    description: "First company to teleport a scent digitally. Building AI models for digital olfaction to understand, digitize, and recreate scents. Giving computers a sense of smell.",
    thesis: "Digitizing smell unlocks applications from disease detection to food science to perfumery — Osmo cracked the code.",
    founder: "Alex Wiltschko",
    location: "Cambridge, MA",
    state: "MA",
    lat: 42.3736,
    lng: -71.1097,
    stage: "Series B",
    founded: 2022,
    fundingStage: "Series B",
    totalRaised: "$100M+",
    valuation: "",
    investors: ["Google Ventures", "Lux Capital"],
    tags: ["AI", "olfaction", "scent", "sensors", "digital smell"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    rosCoverage: "Rational Optimist Awards - first scent teleportation"
  },
  {
    name: "Alpha School",
    sector: "Education",
    description: "Revolutionary K-12 education with two-hour school days enabled by AI-powered personalized learning. Students consistently score in top 1% nationally.",
    thesis: "If AI can personalize learning, why do we need 6-hour school days? Alpha proves we don't.",
    founder: "MacKenzie Price",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Early Stage",
    founded: 2019,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    investors: [],
    tags: ["education", "AI", "school", "personalized learning"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    rosCoverage: "Site visit, Rational Optimist Awards"
  },

  // ─── OCEAN TECH ───
  {
    name: "Ulysses Robotics",
    sector: "Ocean Tech",
    description: "Ocean robotics company building autonomous underwater systems for seagrass planting and ecosystem restoration. $1M first-year revenue.",
    thesis: "The ocean is the next frontier — underwater autonomy for restoration, exploration, and infrastructure.",
    founder: "Will O'Brien",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "$2M+",
    valuation: "",
    investors: [],
    tags: ["ocean tech", "robotics", "underwater autonomy", "seagrass"],
    rosLink: "https://rationaloptimistsociety.substack.com/p/spacex-of-the-sea",
    rosCoverage: "Featured in 'SpaceX of the Sea' article"
  }
];

// Sector categories for filtering
const SECTORS = [
  "Defense & Security",
  "Nuclear Energy",
  "Robotics & Manufacturing",
  "Space & Aerospace",
  "Supersonic & Hypersonic",
  "Climate & Energy",
  "Biotech & Health",
  "Consumer Tech",
  "Education",
  "Ocean Tech"
];

// Funding stages for filtering
const STAGES = [
  "Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series D",
  "Late Stage",
  "Early Stage"
];
