// ═══════════════════════════════════════════════════════════════════════════
// ROS STARTUP DATABASE
// Companies featured by the Rational Optimist Society
// Last updated: February 2026
// ═══════════════════════════════════════════════════════════════════════════

const COMPANIES = [
  // ═══════════════════════════════════════════════════════════════════════════
  // DEFENSE & SECURITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Anduril Industries",
    sector: "Defense & Security",
    description: "Most valuable US defense startup. Pentagon selected them for Air Force's flagship AI drone program. Building 1,000 unmanned aircraft by 2030. Products include Fury drone (attacks in swarms at 700 mph), Roadrunner interceptor, Ghost recon drone, and Lattice OS.",
    thesis: "Lattice OS is becoming the de facto operating system for autonomous defense. Their vertical integration strategy mirrors early SpaceX.",
    founder: "Palmer Luckey, Brian Schimpf, Trae Stephens",
    location: "Costa Mesa, CA",
    state: "CA",
    lat: 33.6846,
    lng: -117.8265,
    stage: "Series G",
    founded: 2017,
    fundingStage: "Series G",
    totalRaised: "$2.5B+",
    valuation: "$78B+",
    investors: ["Founders Fund", "a16z", "General Catalyst", "8VC"],
    tags: ["autonomous drones", "AI", "defense", "Lattice OS", "Roadrunner"],
    rosArticle: "The New Air Force, The Next Silicon Valley, SpaceX of the Sea",
    rosCoverage: "Featured in multiple articles and Rational Optimist Awards"
  },
  {
    name: "Saronic",
    sector: "Defense & Security",
    description: "Autonomous surface vessels built at shipyard scale through Port Alpha shipyard. Vertically integrated 'shipyard as startup' producing Spyglass, Corsair, and Marauder autonomous vessels for naval defense.",
    thesis: "Building autonomous naval vessels on software development timelines, not traditional shipbuilding cycles. The Navy desperately needs this speed.",
    founder: "Dino Mavrookas",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Late Stage",
    founded: 2022,
    fundingStage: "Late Stage",
    totalRaised: "$600M+",
    valuation: "$4.0B",
    investors: ["a16z"],
    tags: ["autonomous", "naval", "shipbuilding", "defense"],
    rosArticle: "SpaceX of the Sea, Shady Stuff Underwater",
    rosCoverage: "Featured article: 'SpaceX of the Sea'"
  },
  {
    name: "Neros",
    sector: "Defense & Security",
    description: "America's #1 drone maker. First mass-scale US drone made entirely from non-Chinese components. Producing ~1,000 drones monthly. Goal to make 100,000 drones annually. Factory under construction in El Segundo.",
    thesis: "FPV drones are the new infantry weapon. Neros is scaling American drone manufacturing to meet urgent military demand.",
    founder: "Soren Monroe-Anderson, Olaf Hichwa",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series B",
    founded: 2022,
    fundingStage: "Series B",
    totalRaised: "$110M+",
    valuation: "",
    investors: ["Sequoia Capital"],
    tags: ["FPV drones", "manufacturing", "defense", "Ukraine"],
    rosArticle: "The $65 Million Cube, Sky Wars, Rational Optimist Awards",
    rosCoverage: "Site visit, Rational Optimist Awards"
  },
  {
    name: "Allen Control Systems",
    sector: "Defense & Security",
    description: "Manufactures Bullfrog AI-enabled turret (165 lbs) that mounts machine guns for drone defense. Achieves ~$10 cost-per-kill against drones. Demonstrated swarm engagement capabilities at DoD events.",
    thesis: "At $10 per kill vs $100K+ missiles, the economics are transformative for counter-drone warfare.",
    founder: "Steve Simoni",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$42M",
    valuation: "",
    investors: ["Craft Ventures"],
    tags: ["counter-drone", "gun turret", "autonomous", "defense", "Bullfrog"],
    rosArticle: "Austin + Detroit = Winning",
    rosCoverage: "Podcast interview with founder Steve Simoni"
  },
  {
    name: "Flyby Robotics",
    sector: "Defense & Security",
    description: "AI-powered autonomous drone systems. Building 'flying brains' that can operate independently without human pilots using advanced computer vision. Mission to restore America's industrial UAV fleet.",
    thesis: "Autonomous drones need to think for themselves — Flyby is building the AI that makes that possible.",
    founder: "Jason Lu, Cat Orman",
    location: "Los Angeles, CA",
    state: "CA",
    lat: 34.0522,
    lng: -118.2437,
    stage: "Seed",
    founded: 2020,
    fundingStage: "Seed",
    totalRaised: "$4M+",
    valuation: "",
    investors: ["MaC Venture Capital", "Naval Ravikant"],
    tags: ["autonomous drones", "AI", "computer vision", "industrial UAV"],
    rosArticle: "Drones Just Got Scary Smart",
    rosCoverage: "Podcast episode with founder Jason Lu"
  },
  {
    name: "Shield AI",
    sector: "Defense & Security",
    description: "Fully autonomous drones operating without GPS, immune to jamming. Coordinated swarm technology for defense applications.",
    thesis: "GPS-denied environments are the future of warfare. Shield AI's autonomy stack works where others fail.",
    founder: "Brandon Tseng, Ryan Tseng",
    location: "San Diego, CA",
    state: "CA",
    lat: 32.7157,
    lng: -117.1611,
    stage: "Series F",
    founded: 2015,
    fundingStage: "Series F",
    totalRaised: "$500M+",
    valuation: "$2.8B",
    investors: ["a16z", "Riot Ventures"],
    tags: ["autonomous drones", "GPS-denied", "swarm", "AI"],
    rosArticle: "The Next Silicon Valley",
    rosCoverage: "Featured article"
  },
  {
    name: "Epirus",
    sector: "Defense & Security",
    description: "Microwave weapons that disable drone electronics. US Marines purchased portable versions. High-powered microwave (HPM) systems.",
    thesis: "Directed energy weapons offer unlimited 'ammunition' at near-zero cost per shot.",
    founder: "Leigh Madden",
    location: "Los Angeles, CA",
    state: "CA",
    lat: 34.0522,
    lng: -118.2437,
    stage: "Series D",
    founded: 2018,
    fundingStage: "Series D",
    totalRaised: "$250M+",
    valuation: "",
    investors: ["8VC", "Bedrock"],
    tags: ["directed energy", "microwave weapons", "counter-drone"],
    rosArticle: "The Next Silicon Valley",
    rosCoverage: "Featured article"
  },
  {
    name: "Castelion",
    sector: "Defense & Security",
    description: "Former SpaceX engineers developing hypersonic missiles. Tests weekly in California desert with rapid iteration approach.",
    thesis: "Applying SpaceX's rapid iteration methodology to hypersonic weapons development.",
    founder: "Bryon Hargis",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series B",
    founded: 2022,
    fundingStage: "Series B",
    totalRaised: "$450M+",
    valuation: "",
    investors: ["a16z", "Founders Fund"],
    tags: ["hypersonic", "missiles", "SpaceX alumni"],
    rosArticle: "The Next Silicon Valley",
    rosCoverage: "Featured article"
  },
  {
    name: "Skydio",
    sector: "Defense & Security",
    description: "Previously the largest US drone maker at 10,000 units/year. Autonomous drone technology with advanced obstacle avoidance.",
    thesis: "American-made autonomous drones for enterprise and defense.",
    founder: "Adam Bry",
    location: "San Mateo, CA",
    state: "CA",
    lat: 37.5630,
    lng: -122.3255,
    stage: "Series E",
    founded: 2014,
    fundingStage: "Series E",
    totalRaised: "$340M+",
    valuation: "$2.2B",
    investors: ["a16z", "IVP"],
    tags: ["autonomous drones", "enterprise", "defense"],
    rosArticle: "The $65 Million Cube, Sky Wars",
    rosCoverage: "Mentioned as context for US drone industry"
  },
  {
    name: "Flock Safety",
    sector: "Defense & Security",
    description: "Atlanta-based company with 80,000 AI-powered cameras for crime-fighting. Developing rooftop drone systems for public safety.",
    thesis: "AI-powered surveillance at scale for safer communities.",
    founder: "Garrett Langley",
    location: "Atlanta, GA",
    state: "GA",
    lat: 33.7490,
    lng: -84.3880,
    stage: "Series E",
    founded: 2017,
    fundingStage: "Series E",
    totalRaised: "$380M+",
    valuation: "$4B+",
    investors: ["a16z", "Tiger Global"],
    tags: ["AI cameras", "public safety", "crime prevention"],
    rosArticle: "Rational Optimists Take America",
    rosCoverage: "Featured during America tour"
  },
  {
    name: "Palantir",
    sector: "Defense & Security",
    description: "Software for military logistics and intelligence. Also serves civilian clients. Co-founded by Joe Lonsdale and Peter Thiel.",
    thesis: "Data integration and analysis at scale for defense and enterprise.",
    founder: "Peter Thiel, Joe Lonsdale, Alex Karp",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    stage: "Public",
    founded: 2003,
    fundingStage: "Public",
    totalRaised: "$3B+",
    valuation: "Public",
    investors: ["Founders Fund", "In-Q-Tel"],
    tags: ["software", "defense", "intelligence", "data"],
    rosArticle: "The Next Silicon Valley",
    rosCoverage: "Referenced as defense tech pioneer"
  },
  {
    name: "Hadrian",
    sector: "Defense & Security",
    description: "AI-powered robotics for defense manufacturing. Automated factories churn out defense components 10x faster at half the cost. Serves SpaceX, Lockheed Martin.",
    thesis: "While everyone builds weapons systems, someone has to machine the parts — and US capacity is dangerously thin.",
    founder: "Chris Power",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8358,
    lng: -118.3406,
    stage: "Series C",
    founded: 2020,
    fundingStage: "Series C",
    totalRaised: "$260M+",
    valuation: "$1.6B",
    investors: ["a16z", "Lux Capital", "Founders Fund"],
    tags: ["automated factory", "CNC", "aerospace", "defense manufacturing"],
    rosArticle: "How America Builds Real Things Again, The Next Silicon Valley",
    rosCoverage: "#1 manufacturing startup pick, site visit"
  },
  {
    name: "Poseidon Aerospace",
    sector: "Defense & Security",
    description: "Ekranoplan-based autonomous vessels. Building Seagull (13-foot craft, 120-mile range) and Heron (50-foot, 1,500 miles) ground-effect vehicles.",
    thesis: "Ground-effect vehicles combine the speed of aircraft with the efficiency of ships.",
    founder: "",
    location: "San Diego, CA",
    state: "CA",
    lat: 32.7157,
    lng: -117.1611,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$12M+",
    valuation: "",
    investors: [],
    tags: ["ekranoplan", "maritime", "autonomous", "ground-effect"],
    rosArticle: "Shady Stuff Underwater, SpaceX of the Sea",
    rosCoverage: "Featured article"
  },
  {
    name: "Amidon Heavy Industries",
    sector: "Defense & Security",
    description: "Subsea inspection and monitoring robots for underwater infrastructure and defense applications.",
    thesis: "The ocean floor is critical infrastructure that needs constant monitoring.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "",
    valuation: "",
    investors: [],
    tags: ["subsea", "inspection", "underwater robots"],
    rosArticle: "Shady Stuff Underwater",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NUCLEAR ENERGY / SMR
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Valar Atomics",
    sector: "Nuclear Energy",
    description: "First and only SMR startup to split the atom. Founded by Isaiah Taylor, who taught himself nuclear physics. Completed controlled chain reaction; broke ground on Ward 250 reactor in Utah. Business model: use nuclear to create hydrogen, then bond with CO2 for clean jet fuel.",
    thesis: "Nuclear-powered synthetic fuels could disrupt the $4T hydrocarbon market.",
    founder: "Isaiah Taylor",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series A",
    founded: 2023,
    fundingStage: "Series A",
    totalRaised: "$149M",
    valuation: "",
    investors: [],
    tags: ["SMR", "nuclear", "synthetic fuels", "HALEU"],
    rosArticle: "SMR Power Rankings (#1), The Standard Oil of Nuclear, Rational Optimist Awards",
    rosCoverage: "Ranked #1 in SMR Power Rankings"
  },
  {
    name: "Radiant",
    sector: "Nuclear Energy",
    description: "Portable 1.2MW nuclear microreactors. Secured site for R-50 Factory in Oak Ridge, TN to produce 50 reactors/year. Deal with US Army for Air Force base deployment within 36 months.",
    thesis: "1.2MW that fits on a truck and powers a forward operating base without fuel convoys.",
    founder: "Doug Bernauer",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series D",
    founded: 2020,
    fundingStage: "Series D",
    totalRaised: "$465M+",
    valuation: "",
    investors: [],
    tags: ["microreactor", "nuclear", "portable", "defense"],
    rosArticle: "SMR Power Rankings (#2), The Standard Oil of Nuclear",
    rosCoverage: "Ranked #2 in SMR Power Rankings"
  },
  {
    name: "Aalo Atomics",
    sector: "Nuclear Energy",
    description: "Building nuclear reactors small enough for a Manhattan apartment. SMR factory in Austin; broke ground in Idaho for Aalo-X test reactor. Goal to turn on reactor by July 4, 2026. Signed deal with Urenco for enriched uranium.",
    thesis: "The fastest path to deployed nuclear is using what already exists.",
    founder: "Matt Loszak",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    investors: [],
    tags: ["SMR", "nuclear", "data centers", "Austin"],
    rosArticle: "SMR Power Rankings (#3), The First Nuclear SMR, Austin + Detroit",
    rosCoverage: "Site visit, Ranked #3 in SMR Power Rankings"
  },
  {
    name: "Kairos Power",
    sector: "Nuclear Energy",
    description: "Made deal with Google to build microreactors. Completed non-nuclear part of Hermes reactor in Oak Ridge. Targeting mid-2026 activation. In 'pole position' to be first startup to flip switch on civilian SMR.",
    thesis: "Google's backing positions Kairos as the frontrunner for first commercial SMR deployment.",
    founder: "Mike Laufer, Edward Blandford",
    location: "Alameda, CA",
    state: "CA",
    lat: 37.7652,
    lng: -122.2416,
    stage: "Late Stage",
    founded: 2016,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "",
    investors: ["Google"],
    tags: ["SMR", "nuclear", "molten salt", "Google"],
    rosArticle: "SMR Power Rankings (#4), The First Nuclear SMR",
    rosCoverage: "Ranked #4 in SMR Power Rankings"
  },
  {
    name: "Antares",
    sector: "Nuclear Energy",
    description: "Selected by Defense Innovation Unit for fast-track program. Raised $96M for 'Mark-0' test reactor. Making its own TRISO fuel. Goal to go critical at Idaho National Labs.",
    thesis: "Defense applications provide the fastest path to deployed microreactors.",
    founder: "",
    location: "Washington, DC",
    state: "DC",
    lat: 38.9072,
    lng: -77.0369,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$96M",
    valuation: "",
    investors: [],
    tags: ["SMR", "microreactor", "TRISO", "defense"],
    rosArticle: "SMR Power Rankings (#5), The Next Silicon Valley",
    rosCoverage: "Ranked #5 in SMR Power Rankings"
  },
  {
    name: "General Matter",
    sector: "Nuclear Energy",
    description: "Rebuilding American uranium enrichment capacity for next-gen nuclear fuels. Founders Fund-incubated. Reopening Paducah, Kentucky facility. $900M DOE HALEU contract.",
    thesis: "No HALEU fuel means no advanced reactors. General Matter is solving the supply chain.",
    founder: "Scott Nolan, Lee Robinson",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9170,
    lng: -118.4160,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$50M+",
    valuation: "",
    investors: ["Founders Fund"],
    tags: ["uranium", "enrichment", "nuclear fuel", "HALEU"],
    rosArticle: "The Standard Oil of Nuclear, The First Nuclear SMR",
    rosCoverage: "Featured article"
  },
  {
    name: "Oklo",
    sector: "Nuclear Energy",
    description: "Signed huge deal with Meta for 1.2-gigawatt nuclear campus in Pike County, Ohio. Power purchase agreement with Equinix. Broke ground at Eielson Air Force Base in Alaska.",
    thesis: "Data center demand is driving nuclear's comeback.",
    founder: "Jacob DeWitte, Caroline Cochran",
    location: "Santa Clara, CA",
    state: "CA",
    lat: 37.3541,
    lng: -121.9552,
    stage: "Public",
    founded: 2013,
    fundingStage: "Public",
    totalRaised: "$300M+",
    valuation: "Public",
    investors: ["Sam Altman"],
    tags: ["SMR", "nuclear", "Meta", "data centers"],
    rosArticle: "SMR Power Rankings",
    rosCoverage: "Featured in SMR rankings"
  },
  {
    name: "X-Energy",
    sector: "Nuclear Energy",
    description: "Amazon anchored $500M funding round for AI data center SMRs. Deals with Pentagon/Air Force and Centrica UK for 12 SMRs.",
    thesis: "TRISO fuel provides inherent safety that enables new deployment scenarios.",
    founder: "Kam Ghaffarian",
    location: "Rockville, MD",
    state: "MD",
    lat: 39.0840,
    lng: -77.1528,
    stage: "Late Stage",
    founded: 2009,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "",
    investors: ["Amazon"],
    tags: ["SMR", "nuclear", "TRISO", "Amazon"],
    rosArticle: "SMR Power Rankings",
    rosCoverage: "Featured in SMR rankings"
  },
  {
    name: "TerraPower",
    sector: "Nuclear Energy",
    description: "Landed deal with Meta to fund two Natrium reactors. Non-nuclear construction nearly complete in Kemmerer, WY.",
    thesis: "Bill Gates-backed advanced nuclear is finally becoming reality.",
    founder: "Bill Gates",
    location: "Bellevue, WA",
    state: "WA",
    lat: 47.6101,
    lng: -122.2015,
    stage: "Late Stage",
    founded: 2008,
    fundingStage: "Late Stage",
    totalRaised: "$1B+",
    valuation: "",
    investors: ["Bill Gates", "Meta"],
    tags: ["SMR", "nuclear", "Natrium", "Meta"],
    rosArticle: "SMR Power Rankings",
    rosCoverage: "Featured in SMR rankings"
  },
  {
    name: "Last Energy",
    sector: "Nuclear Energy",
    description: "Signed £80M deal in UK for 12 microreactors. Got permission to plug into UK national grid. Deal to power data centers in Haskell County, Texas.",
    thesis: "Modular reactors for distributed power generation.",
    founder: "Bret Kugelmass",
    location: "Washington, DC",
    state: "DC",
    lat: 38.9072,
    lng: -77.0369,
    stage: "Series B",
    founded: 2020,
    fundingStage: "Series B",
    totalRaised: "$100M+",
    valuation: "",
    investors: [],
    tags: ["SMR", "microreactor", "UK", "data centers"],
    rosArticle: "SMR Power Rankings (#9), The First Nuclear SMR",
    rosCoverage: "Ranked #9 in SMR Power Rankings"
  },
  {
    name: "Deep Fission",
    sector: "Nuclear Energy",
    description: "Burying microreactors one mile underground. Drilling 30-inch borehole for underground reactor. Raised $30M. Selected by DOE Reactor Pilot Program.",
    thesis: "Underground deployment eliminates siting concerns and security requirements.",
    founder: "",
    location: "Houston, TX",
    state: "TX",
    lat: 29.7604,
    lng: -95.3698,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$30M",
    valuation: "",
    investors: [],
    tags: ["microreactor", "underground", "DOE"],
    rosArticle: "SMR Power Rankings (#15 Rookie)",
    rosCoverage: "Ranked #15 (Rookie) in SMR Power Rankings"
  },
  {
    name: "Terrestrial Energy",
    sector: "Nuclear Energy",
    description: "Selected by DOE Reactor Pilot Program. Building molten salt reactor with replaceable 'Core-Can' design. RELLIS campus Texas.",
    thesis: "Molten salt reactors offer inherent safety and fuel flexibility.",
    founder: "Simon Irish",
    location: "New York, NY",
    state: "NY",
    lat: 40.7128,
    lng: -74.0060,
    stage: "Late Stage",
    founded: 2013,
    fundingStage: "Late Stage",
    totalRaised: "$100M+",
    valuation: "",
    investors: [],
    tags: ["SMR", "molten salt", "DOE"],
    rosArticle: "SMR Power Rankings, The First Nuclear SMR",
    rosCoverage: "Featured in SMR rankings"
  },
  {
    name: "Natura Resources",
    sector: "Nuclear Energy",
    description: "Molten-salt reactor at Abilene Christian University. DOE nuclear fuel allocation. Permian Basin deployment with desalination.",
    thesis: "Nuclear-powered desalination solves water and energy simultaneously.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2020,
    fundingStage: "Series A",
    totalRaised: "$50M+",
    valuation: "",
    investors: [],
    tags: ["SMR", "molten salt", "desalination", "Permian"],
    rosArticle: "SMR Power Rankings, The First Nuclear SMR",
    rosCoverage: "Featured in SMR rankings"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FUSION ENERGY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Commonwealth Fusion Systems",
    sector: "Fusion Energy",
    description: "Massachusetts-based. Raised nearly $3 billion. Targeting net energy from compact tokamak by 2027. High-temperature superconducting magnets enable smaller reactors.",
    thesis: "HTS magnets are the breakthrough that makes commercial fusion economics work.",
    founder: "Bob Mumgaard",
    location: "Devens, MA",
    state: "MA",
    lat: 42.5376,
    lng: -71.6131,
    stage: "Late Stage",
    founded: 2018,
    fundingStage: "Late Stage",
    totalRaised: "$2B+",
    valuation: "",
    investors: ["Bill Gates", "Google", "Tiger Global"],
    tags: ["fusion", "tokamak", "HTS magnets"],
    rosArticle: "Are We Finally About to Crack Fusion",
    rosCoverage: "Featured article on fusion"
  },
  {
    name: "Xcimer Energy",
    sector: "Fusion Energy",
    description: "Colorado-based. Inertial confinement fusion using lasers fired at falling fuel capsules. Novel approach to laser fusion.",
    thesis: "Simplified laser fusion architecture dramatically reduces costs.",
    founder: "",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$100M+",
    valuation: "",
    investors: ["Breakthrough Energy Ventures"],
    tags: ["fusion", "laser", "inertial confinement"],
    rosArticle: "Are We Finally About to Crack Fusion",
    rosCoverage: "Featured article on fusion"
  },
  {
    name: "Helion Energy",
    sector: "Fusion Energy",
    description: "Washington state-based. Field-reversed configuration technology, firing plasma balls. Signed PPA with Microsoft for 2028 delivery.",
    thesis: "Direct electricity conversion from fusion plasma eliminates steam turbines.",
    founder: "David Kirtley",
    location: "Everett, WA",
    state: "WA",
    lat: 47.9790,
    lng: -122.2021,
    stage: "Late Stage",
    founded: 2013,
    fundingStage: "Late Stage",
    totalRaised: "$600M+",
    valuation: "",
    investors: ["Sam Altman", "Dustin Moskovitz"],
    tags: ["fusion", "field-reversed", "Microsoft"],
    rosArticle: "Are We Finally About to Crack Fusion",
    rosCoverage: "Featured article on fusion"
  },
  {
    name: "TAE Technologies",
    sector: "Fusion Energy",
    description: "California-based. Field-reversed configuration. Achieved proton-boron fusion in 2023 — aneutronic fusion produces no neutron radiation.",
    thesis: "Proton-boron fusion is cleaner and enables direct energy conversion.",
    founder: "Michl Binderbauer",
    location: "Foothill Ranch, CA",
    state: "CA",
    lat: 33.6869,
    lng: -117.6603,
    stage: "Late Stage",
    founded: 1998,
    fundingStage: "Late Stage",
    totalRaised: "$1.2B+",
    valuation: "",
    investors: ["Google", "Venrock"],
    tags: ["fusion", "proton-boron", "aneutronic"],
    rosArticle: "Are We Finally About to Crack Fusion",
    rosCoverage: "Featured article on fusion"
  },
  {
    name: "Tokamak Energy",
    sector: "Fusion Energy",
    description: "British company. First private organization to achieve 100-million-degree threshold for fusion (2022). Compact spherical tokamak design.",
    thesis: "Spherical tokamaks offer better plasma confinement in smaller packages.",
    founder: "",
    location: "Oxford, UK",
    state: "",
    lat: 51.7520,
    lng: -1.2577,
    stage: "Late Stage",
    founded: 2009,
    fundingStage: "Late Stage",
    totalRaised: "$250M+",
    valuation: "",
    investors: [],
    tags: ["fusion", "tokamak", "UK"],
    rosArticle: "Are We Finally About to Crack Fusion",
    rosCoverage: "Featured article on fusion"
  },
  {
    name: "OpenStar",
    sector: "Fusion Energy",
    description: "New Zealand fusion startup that created and contained plasma cloud at 540,000 degrees Fahrenheit in first experimental reactor.",
    thesis: "Novel approaches from unexpected places may crack fusion.",
    founder: "",
    location: "Auckland, New Zealand",
    state: "",
    lat: -36.8485,
    lng: 174.7633,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "$10M+",
    valuation: "",
    investors: [],
    tags: ["fusion", "plasma", "New Zealand"],
    rosArticle: "How America Builds",
    rosCoverage: "Mentioned in manufacturing article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ROBOTICS & MANUFACTURING
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Machina Labs",
    sector: "Robotics & Manufacturing",
    description: "Pioneered robo-forming technology for sheet-metal. Dual robot arms work in sync. Toyota partnership for auto body panels. Air Force contract. Serves $250B industry.",
    thesis: "Robo-forming makes metal shaping as flexible as 3D printing but at production scale.",
    founder: "Ed Mehr",
    location: "Chatsworth, CA",
    state: "CA",
    lat: 34.2572,
    lng: -118.6012,
    stage: "Series B",
    founded: 2019,
    fundingStage: "Series B",
    totalRaised: "$80M+",
    valuation: "",
    investors: ["NVentures", "Innovation Endeavors", "Lockheed Martin Ventures"],
    tags: ["robotic manufacturing", "metal forming", "Toyota", "roboforming"],
    rosArticle: "Going Robotic, The First Nuclear SMR",
    rosCoverage: "Featured article: 'Going Robotic'"
  },
  {
    name: "Rangeview",
    sector: "Robotics & Manufacturing",
    description: "'Cyber foundry' with robotic arms. 3D printing casts for investment casting, cutting 8 steps from 18-step process. Air Force SBIR for turbine components.",
    thesis: "Automated foundry cuts production from months to hours.",
    founder: "Aeden Gasser-Brennan, Cameron Schiller",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9185,
    lng: -118.4155,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    investors: [],
    tags: ["casting", "foundry", "robotics", "3D printing"],
    rosArticle: "How America Builds Real Things Again",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "DIRAC",
    sector: "Robotics & Manufacturing",
    description: "'Anti-software software company' for manufacturing. BuildOS product — 'like ChatGPT for mechanical engineers.' Converts CAD to assembly instructions in minutes.",
    thesis: "Bad work instructions cause defects and slowdowns. DIRAC fixes manufacturing's most overlooked problem.",
    founder: "Fil Aronshtein",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    investors: [],
    tags: ["manufacturing", "work instructions", "AI", "BuildOS"],
    rosArticle: "How America Builds Real Things Again",
    rosCoverage: "Featured article"
  },
  {
    name: "Bedrock Robotics",
    sector: "Robotics & Manufacturing",
    description: "Founded by three Waymo veterans. Makes smart kits with cameras/sensors for autonomous construction equipment. Targeting $2T construction industry with 800,000 worker shortage.",
    thesis: "Why replace a $500K excavator when you can make it autonomous for a fraction of the cost?",
    founder: "Boris Sofman, Mory Gharib",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series B",
    founded: 2023,
    fundingStage: "Series B",
    totalRaised: "$350M+",
    valuation: "$1.75B",
    investors: ["8VC"],
    tags: ["autonomous construction", "heavy equipment", "Waymo alumni"],
    rosArticle: "Austin + Detroit = Winning, Going Robotic",
    rosCoverage: "Featured article"
  },
  {
    name: "Physical Intelligence",
    sector: "Robotics & Manufacturing",
    description: "Building AI system that plugs into many robot types — like ChatGPT for robots / operating system for physical world. Generalist brain for robotics.",
    thesis: "One AI model to control all robots, regardless of form factor.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2024,
    fundingStage: "Series A",
    totalRaised: "$400M+",
    valuation: "",
    investors: ["Jeff Bezos", "OpenAI", "Thrive Capital"],
    tags: ["AI", "robotics", "foundation model"],
    rosArticle: "Going Robotic, Rise of the Automaton",
    rosCoverage: "Featured article"
  },
  {
    name: "Figure AI",
    sector: "Robotics & Manufacturing",
    description: "Unveiled humanoid helper 'Helix' that can pick up virtually any household object. Raised $675M from Microsoft, OpenAI, NVIDIA, Jeff Bezos.",
    thesis: "General-purpose humanoid robots for household and industrial tasks.",
    founder: "Brett Adcock",
    location: "San Jose, CA",
    state: "CA",
    lat: 37.3382,
    lng: -121.8863,
    stage: "Series B",
    founded: 2022,
    fundingStage: "Series B",
    totalRaised: "$675M+",
    valuation: "$2.6B",
    investors: ["Microsoft", "OpenAI", "NVIDIA", "Bezos"],
    tags: ["humanoid robot", "AI", "household"],
    rosArticle: "The Year of the Robot, Rise of the Automaton, Going Robotic",
    rosCoverage: "Featured article"
  },
  {
    name: "Clone Robotics",
    sector: "Robotics & Manufacturing",
    description: "Released 'Protoclone' — first bipedal musculoskeletal android with 200+ degrees of freedom, 1,000 Myofibers. Most human-like robot ever built.",
    thesis: "Biomimetic design enables unprecedented dexterity and natural movement.",
    founder: "",
    location: "Warsaw, Poland",
    state: "",
    lat: 52.2297,
    lng: 21.0122,
    stage: "Seed",
    founded: 2021,
    fundingStage: "Seed",
    totalRaised: "$10M+",
    valuation: "",
    investors: [],
    tags: ["humanoid robot", "biomimetic", "musculoskeletal"],
    rosArticle: "The Year of the Robot",
    rosCoverage: "Featured article"
  },
  {
    name: "1X Technologies",
    sector: "Robotics & Manufacturing",
    description: "Neo humanoid robot for household tasks. Uses VR joysticks for training. Norwegian company with OpenAI backing.",
    thesis: "Teleoperation training creates scalable data for robot learning.",
    founder: "Bernt Øivind Børnich",
    location: "Oslo, Norway",
    state: "",
    lat: 59.9139,
    lng: 10.7522,
    stage: "Series B",
    founded: 2014,
    fundingStage: "Series B",
    totalRaised: "$125M+",
    valuation: "",
    investors: ["OpenAI", "Tiger Global"],
    tags: ["humanoid robot", "household", "VR training"],
    rosArticle: "Rise of the Automaton, Going Robotic",
    rosCoverage: "Featured article"
  },
  {
    name: "Boston Dynamics",
    sector: "Robotics & Manufacturing",
    description: "Atlas humanoid robot. Robotic arms for box-unloading. Pioneer in dynamic robotics and legged locomotion.",
    thesis: "Advanced mobility enables robots to work in human environments.",
    founder: "Marc Raibert",
    location: "Waltham, MA",
    state: "MA",
    lat: 42.3765,
    lng: -71.2356,
    stage: "Acquired",
    founded: 1992,
    fundingStage: "Acquired",
    totalRaised: "",
    valuation: "",
    investors: ["Hyundai"],
    tags: ["humanoid robot", "quadruped", "Atlas", "Spot"],
    rosArticle: "Rise of the Automaton, Going Robotic",
    rosCoverage: "Featured article"
  },
  {
    name: "Matic Robots",
    sector: "Robotics & Manufacturing",
    description: "Autonomous home cleaning robot. Software-first approach with advanced navigation and mapping.",
    thesis: "Software intelligence makes robots useful in unstructured home environments.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2020,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    investors: [],
    tags: ["home robot", "cleaning", "autonomous"],
    rosArticle: "Rational Optimist Awards, Rise of the Automaton, Going Robotic",
    rosCoverage: "Featured article"
  },
  {
    name: "RightHand Robotics",
    sector: "Robotics & Manufacturing",
    description: "Computer vision with suction devices and tactile 'fingers' for warehouse automation. Piece-picking robots.",
    thesis: "AI-powered manipulation solves the last challenge in warehouse automation.",
    founder: "",
    location: "Somerville, MA",
    state: "MA",
    lat: 42.3876,
    lng: -71.0995,
    stage: "Series C",
    founded: 2014,
    fundingStage: "Series C",
    totalRaised: "$60M+",
    valuation: "",
    investors: [],
    tags: ["warehouse", "picking", "manipulation"],
    rosArticle: "Rise of the Automaton",
    rosCoverage: "Featured article"
  },
  {
    name: "Locus Robotics",
    sector: "Robotics & Manufacturing",
    description: "Competing with Amazon in warehouse robotics. Autonomous mobile robots for fulfillment centers.",
    thesis: "AMRs work alongside humans to dramatically increase warehouse productivity.",
    founder: "",
    location: "Wilmington, MA",
    state: "MA",
    lat: 42.5584,
    lng: -71.1766,
    stage: "Series F",
    founded: 2014,
    fundingStage: "Series F",
    totalRaised: "$400M+",
    valuation: "$1B+",
    investors: [],
    tags: ["warehouse", "AMR", "fulfillment"],
    rosArticle: "Rise of the Automaton",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AEROSPACE / SUPERSONIC / HYPERSONIC
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Boom Supersonic",
    sector: "Supersonic & Hypersonic",
    description: "XB-1 test jet broke sound barrier 3 times in one flight. North Carolina Superfactory can make 33 jets/year. Building full-sized Overture supersonic jet. NY to London in 3.5 hours. 130+ orders from airlines.",
    thesis: "Proprietary Symphony engines are the unlock — no one else is building a purpose-built supersonic commercial engine.",
    founder: "Blake Scholl",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    stage: "Late Stage",
    founded: 2014,
    fundingStage: "Late Stage",
    totalRaised: "$700M+",
    valuation: "$1.5B",
    investors: ["Y Combinator", "Bessemer"],
    tags: ["supersonic", "aviation", "Overture", "Symphony engine"],
    rosArticle: "Dude Where's My Supersonic Jet, Shhhh Supersonic, Rational Optimist Awards",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "Hermeus",
    sector: "Supersonic & Hypersonic",
    description: "Atlanta-based hypersonic jet startup. Building reusable autonomous military aircraft 'Darkhorse' (Mach 5). Future Halcyon passenger jet (20-passenger, Mach 5). Quarterhorse program for iterative development.",
    thesis: "DoD will pay for Mach 5 capabilities that commercial aviation won't need for decades.",
    founder: "AJ Piplica",
    location: "Atlanta, GA",
    state: "GA",
    lat: 33.7490,
    lng: -84.3880,
    stage: "Series C",
    founded: 2018,
    fundingStage: "Series C",
    totalRaised: "$200M+",
    valuation: "",
    investors: ["Khosla Ventures", "Founders Fund"],
    tags: ["hypersonic", "Mach 5", "Chimera engine", "Darkhorse"],
    rosArticle: "Dude Where's My Supersonic Jet, Rational Optimist Awards",
    rosCoverage: "Featured article"
  },
  {
    name: "Astro Mechanica",
    sector: "Supersonic & Hypersonic",
    description: "Building turboelectric adaptive engine (part jet/electric fan/rocket). Goal: supersonic travel priced like Southwest — SF to Tokyo under $1,000. Using LNG fuel. Defense-first strategy.",
    thesis: "A single engine architecture that works from takeoff to Mach 5 could unlock both supersonic flight and affordable space access.",
    founder: "Ian Brooke",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2023,
    fundingStage: "Series A",
    totalRaised: "$27M+",
    valuation: "",
    investors: ["a16z", "Lowercarbon Capital", "United Airlines"],
    tags: ["supersonic", "adaptive engine", "LNG", "Y Combinator"],
    rosArticle: "Honey I Shrunk the World, Dude Where's My Supersonic Jet, The $65 Million Cube",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "SpaceX",
    sector: "Space & Aerospace",
    description: "World's most valuable private company. 170+ launches in 2025. Launched more mass into orbit since 2006 than every other US aerospace firm combined. 10,000+ Starlink satellites. Starship development.",
    thesis: "Reusability and vertical integration transformed launch economics.",
    founder: "Elon Musk",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9207,
    lng: -118.3280,
    stage: "Late Stage",
    founded: 2002,
    fundingStage: "Late Stage",
    totalRaised: "$10B+",
    valuation: "$350B+",
    investors: ["Founders Fund", "Sequoia"],
    tags: ["rockets", "Starlink", "Starship", "reusability"],
    rosArticle: "Multiple articles",
    rosCoverage: "Referenced throughout as benchmark"
  },
  {
    name: "Joby Aviation",
    sector: "Supersonic & Hypersonic",
    description: "eVTOL air taxi. NYC launch partnering with Delta. Dubai air taxi service 2026. Manhattan to JFK in 7 minutes.",
    thesis: "Electric vertical takeoff opens urban air mobility.",
    founder: "JoeBen Bevirt",
    location: "Santa Cruz, CA",
    state: "CA",
    lat: 36.9741,
    lng: -122.0308,
    stage: "Public",
    founded: 2009,
    fundingStage: "Public",
    totalRaised: "$2B+",
    valuation: "Public",
    investors: ["Toyota", "Delta"],
    tags: ["eVTOL", "air taxi", "electric aviation"],
    rosArticle: "The Biggest IPO Ever, World's New Fastest Car",
    rosCoverage: "Featured article"
  },
  {
    name: "Archer Aviation",
    sector: "Supersonic & Hypersonic",
    description: "eVTOL. Official air taxi for 2028 LA Olympics. Abu Dhabi air taxi 2026.",
    thesis: "Electric aviation will transform urban transportation.",
    founder: "Brett Adcock, Adam Goldstein",
    location: "San Jose, CA",
    state: "CA",
    lat: 37.3382,
    lng: -121.8863,
    stage: "Public",
    founded: 2018,
    fundingStage: "Public",
    totalRaised: "$1B+",
    valuation: "Public",
    investors: ["United Airlines"],
    tags: ["eVTOL", "air taxi", "LA Olympics"],
    rosArticle: "The Biggest IPO Ever, Rise of the Automaton",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPACE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Apex Space",
    sector: "Space & Aerospace",
    description: "'Foxconn of satellite buses.' Standardized, configurable satellite platforms. $45.9M Space Force contract. Producing 200+ satellites/year. Blank paper to orbit in 12 months for <$10M.",
    thesis: "Satellites shouldn't be bespoke — Apex brings mass production economics to space hardware.",
    founder: "Ian Cinnamon, Max Benassi",
    location: "Playa Vista, CA",
    state: "CA",
    lat: 33.9745,
    lng: -118.4280,
    stage: "Series D",
    founded: 2022,
    fundingStage: "Series D",
    totalRaised: "$400M+",
    valuation: "$1B+",
    investors: ["a16z", "8VC", "Shield Capital"],
    tags: ["satellite buses", "manufacturing", "Space Force"],
    rosArticle: "The Henry Ford of Satellites, SpaceX of the Sea",
    rosCoverage: "Podcast interview with founder Ian Cinnamon"
  },
  {
    name: "AstroForge",
    sector: "Space & Aerospace",
    description: "Asteroid mining satellites. Extracting platinum-group metals. Ore 5,000-10,000x purer than South African mines. Using lasers for in-space refining.",
    thesis: "A single asteroid contains more platinum than has ever been mined on Earth.",
    founder: "Matt Gialich, Jose Acain",
    location: "Huntington Beach, CA",
    state: "CA",
    lat: 33.6595,
    lng: -117.9988,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$55M+",
    valuation: "",
    investors: [],
    tags: ["asteroid mining", "platinum", "space resources", "laser refining"],
    rosArticle: "The $65 Million Cube, Rational Optimist Awards",
    rosCoverage: "Runner-up at Rational Optimist Awards"
  },
  {
    name: "Astranis",
    sector: "Space & Aerospace",
    description: "Satellite company with 150,000 sq ft rocket factory in downtown San Francisco. Small geostationary satellites for dedicated bandwidth.",
    thesis: "GEO satellites don't have to be billion-dollar behemoths.",
    founder: "John Gedmark",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series C",
    founded: 2015,
    fundingStage: "Series C",
    totalRaised: "$350M+",
    valuation: "$1.4B",
    investors: ["a16z", "Venrock"],
    tags: ["GEO satellites", "telecommunications", "bandwidth"],
    rosArticle: "Our Secret Plan, SpaceX of the Sea",
    rosCoverage: "Featured article"
  },
  {
    name: "Varda Space Industries",
    sector: "Space & Aerospace",
    description: "In-space manufacturing. Building pharmaceutical products in microgravity. Successfully returned capsule from orbit.",
    thesis: "Some products can only be made in zero gravity.",
    founder: "Will Bruey, Delian Asparouhov",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    stage: "Series B",
    founded: 2021,
    fundingStage: "Series B",
    totalRaised: "$150M+",
    valuation: "",
    investors: ["Founders Fund", "Khosla Ventures"],
    tags: ["space manufacturing", "pharmaceuticals", "microgravity"],
    rosArticle: "SpaceX of the Sea",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLIMATE & ENERGY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Terraform Industries",
    sector: "Climate & Energy",
    description: "Creating synthetic natural gas from solar power, water, and atmospheric CO2. Modular Terraformer units. 99.4% purity demonstrated.",
    thesis: "If you can make fuel from sunlight and air, you've solved both energy storage and decarbonization.",
    founder: "Casey Handmer",
    location: "Burbank, CA",
    state: "CA",
    lat: 34.1808,
    lng: -118.3090,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$26M",
    valuation: "",
    investors: [],
    tags: ["synthetic fuel", "carbon capture", "solar", "methane"],
    rosArticle: "World's New Fastest Car",
    rosCoverage: "Podcast Episode #44 with founder Casey Handmer"
  },
  {
    name: "Rainmaker",
    sector: "Climate & Energy",
    description: "Using specialized drones to make it rain on demand at fraction of cloud seeding costs. Restored 10 billion gallons to Utah's Great Salt Lake. Founded by 23-year-old Augustus Doricko.",
    thesis: "We have the technology to make it rain — deploy it at scale where water is most needed.",
    founder: "Augustus Doricko",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9188,
    lng: -118.4162,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$25M",
    valuation: "",
    investors: ["Lowercarbon Capital"],
    tags: ["cloud seeding", "weather modification", "water", "drones"],
    rosArticle: "Austin + Detroit = Winning, The Next Silicon Valley",
    rosCoverage: "Featured article"
  },
  {
    name: "Fervo Energy",
    sector: "Climate & Energy",
    description: "Enhanced geothermal using horizontal drilling from oil & gas. First commercial plant operational in Nevada.",
    thesis: "Oil & gas drilling techniques unlock geothermal anywhere.",
    founder: "Tim Latimer",
    location: "Houston, TX",
    state: "TX",
    lat: 29.7604,
    lng: -95.3698,
    stage: "Series C",
    founded: 2017,
    fundingStage: "Series C",
    totalRaised: "$430M+",
    valuation: "",
    investors: ["Breakthrough Energy Ventures", "DCVC"],
    tags: ["geothermal", "drilling", "baseload power"],
    rosArticle: "How Many Lives",
    rosCoverage: "Featured article"
  },
  {
    name: "Quaise Energy",
    sector: "Climate & Energy",
    description: "Laser drilling technology to access deep geothermal. Using millimeter waves to vaporize rock.",
    thesis: "Access Earth's deep heat everywhere for unlimited clean baseload.",
    founder: "Carlos Araque",
    location: "Boston, MA",
    state: "MA",
    lat: 42.3601,
    lng: -71.0589,
    stage: "Series A",
    founded: 2018,
    fundingStage: "Series A",
    totalRaised: "$100M+",
    valuation: "",
    investors: ["Prelude Ventures"],
    tags: ["geothermal", "laser drilling", "deep heat"],
    rosArticle: "How Many Lives",
    rosCoverage: "Featured article"
  },
  {
    name: "Ouros Energy",
    sector: "Climate & Energy",
    description: "Battery cells claimed 10X denser, 100X cheaper than lithium-ion. Novel battery chemistry.",
    thesis: "Step-change in battery economics transforms everything.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "",
    valuation: "",
    investors: [],
    tags: ["batteries", "energy storage"],
    rosArticle: "World's New Fastest Car",
    rosCoverage: "Featured article"
  },
  {
    name: "Impulse Labs",
    sector: "Climate & Energy",
    description: "Battery-powered induction stoves with rapid heating. Consumer appliances.",
    thesis: "Batteries solve the cooking gas problem.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2021,
    fundingStage: "Series A",
    totalRaised: "$25M+",
    valuation: "",
    investors: [],
    tags: ["appliances", "batteries", "induction"],
    rosArticle: "World's New Fastest Car",
    rosCoverage: "Featured article"
  },
  {
    name: "Base Power",
    sector: "Climate & Energy",
    description: "Austin-based. Home battery systems aggregated into virtual power plants.",
    thesis: "Distributed batteries become grid infrastructure.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "",
    valuation: "",
    investors: [],
    tags: ["batteries", "virtual power plant", "grid"],
    rosArticle: "World's New Fastest Car",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AI & TECHNOLOGY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "xAI",
    sector: "AI & Technology",
    description: "Built world's largest AI data center in 122 days on Tennessee-Mississippi border. Grok AI models.",
    thesis: "Speed of execution matters more than perfect planning.",
    founder: "Elon Musk",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series B",
    founded: 2023,
    fundingStage: "Series B",
    totalRaised: "$6B+",
    valuation: "$50B+",
    investors: ["a16z", "Sequoia"],
    tags: ["AI", "data center", "Grok", "LLM"],
    rosArticle: "Rational Optimist Awards, We Must Defeat BANANA",
    rosCoverage: "Featured article"
  },
  {
    name: "OpenAI",
    sector: "AI & Technology",
    description: "ChatGPT. o3 models. Stargate AI project. Partnership with Khan Academy for education.",
    thesis: "AGI development will transform every industry.",
    founder: "Sam Altman",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Late Stage",
    founded: 2015,
    fundingStage: "Late Stage",
    totalRaised: "$14B+",
    valuation: "$150B+",
    investors: ["Microsoft", "Thrive Capital"],
    tags: ["AI", "ChatGPT", "AGI", "LLM"],
    rosArticle: "Multiple articles",
    rosCoverage: "Referenced throughout"
  },
  {
    name: "Midjourney",
    sector: "AI & Technology",
    description: "AI image generation. 40 employees, $500M revenue. Most efficient AI company ever.",
    thesis: "Small teams with great AI can achieve enormous outcomes.",
    founder: "David Holz",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Bootstrapped",
    founded: 2021,
    fundingStage: "Bootstrapped",
    totalRaised: "$0",
    valuation: "",
    investors: [],
    tags: ["AI", "image generation", "generative AI"],
    rosArticle: "AI: Age of Individual",
    rosCoverage: "Featured article"
  },
  {
    name: "Cursor",
    sector: "AI & Technology",
    description: "AI code editor. $100M sales with 20-person team. AI-first development environment.",
    thesis: "AI will write most code, humans will direct it.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$60M+",
    valuation: "",
    investors: ["a16z", "OpenAI"],
    tags: ["AI", "code editor", "developer tools"],
    rosArticle: "AI: Age of Individual",
    rosCoverage: "Featured article"
  },
  {
    name: "Gauntlet AI",
    sector: "AI & Technology",
    description: "'Navy Seals for AI engineers' — 5,000 apply, ~2% accepted, 10-week program guarantees $200K+ starting salary.",
    thesis: "Elite AI talent is the scarcest resource.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Seed",
    founded: 2024,
    fundingStage: "Seed",
    totalRaised: "",
    valuation: "",
    investors: [],
    tags: ["AI training", "bootcamp", "talent"],
    rosArticle: "Austin + Detroit = Winning",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SEMICONDUCTORS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Cerebras",
    sector: "Semiconductors",
    description: "Makes largest computer chips in the world, built specifically for running AI models faster.",
    thesis: "Wafer-scale integration eliminates memory bottlenecks.",
    founder: "Andrew Feldman",
    location: "Sunnyvale, CA",
    state: "CA",
    lat: 37.3688,
    lng: -122.0363,
    stage: "Late Stage",
    founded: 2016,
    fundingStage: "Late Stage",
    totalRaised: "$700M+",
    valuation: "$4B+",
    investors: ["Benchmark"],
    tags: ["chips", "AI hardware", "wafer-scale"],
    rosArticle: "The Chip Rebellion",
    rosCoverage: "Featured article"
  },
  {
    name: "Etched",
    sector: "Semiconductors",
    description: "San Francisco-based. AI-specific chips. Raised money at $5B valuation. Transformer-specific ASICs.",
    thesis: "Purpose-built chips for transformers dramatically outperform GPUs.",
    founder: "Chris Zhu, Robert Wachen",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$125M+",
    valuation: "$5B",
    investors: ["Peter Thiel", "a16z"],
    tags: ["chips", "AI hardware", "ASIC", "transformer"],
    rosArticle: "The Chip Rebellion",
    rosCoverage: "Featured article"
  },
  {
    name: "Extropic",
    sector: "Semiconductors",
    description: "Pioneering thermodynamic computing — 'invented a whole new ball game'. Novel computing paradigm.",
    thesis: "Physics-based computing offers exponential advantages for certain problems.",
    founder: "Guillaume Verdon",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$35M+",
    valuation: "",
    investors: [],
    tags: ["thermodynamic computing", "physics", "novel computing"],
    rosArticle: "The Chip Rebellion",
    rosCoverage: "Featured article"
  },
  {
    name: "Substrate",
    sector: "Semiconductors",
    description: "Founded by James Proud (Thiel Fellow). Building chipmaking machine using X-rays instead of UV light. Goal: slash leading-edge chip wafer cost from $100K to $10K.",
    thesis: "X-ray lithography could democratize advanced chip manufacturing.",
    founder: "James Proud",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2023,
    fundingStage: "Seed",
    totalRaised: "$30M+",
    valuation: "",
    investors: ["Thiel Fellowship"],
    tags: ["lithography", "X-ray", "chip manufacturing"],
    rosArticle: "The Chip Rebellion",
    rosCoverage: "Featured article"
  },
  {
    name: "Lightmatter",
    sector: "Semiconductors",
    description: "Replaces copper wires with fiber-optic connections. Silicon wafer with thousands of tiny pipes for data to travel at speed of light between chips.",
    thesis: "Photonic interconnects eliminate the data movement bottleneck.",
    founder: "Nick Harris",
    location: "Boston, MA",
    state: "MA",
    lat: 42.3601,
    lng: -71.0589,
    stage: "Series C",
    founded: 2017,
    fundingStage: "Series C",
    totalRaised: "$300M+",
    valuation: "",
    investors: ["GV", "Viking Global"],
    tags: ["photonics", "optical interconnect", "data center"],
    rosArticle: "The Chip Rebellion",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEUROTECH & BIOTECH
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Neuralink",
    sector: "Neurotech",
    description: "Brain-computer interface chip. 'Breakthrough device' FDA designation for Blindsight implant. 1,024 microscopic electrodes on 64 threads. Paralyzed patients communicating.",
    thesis: "Direct brain-computer interfaces will restore and enhance human capabilities.",
    founder: "Elon Musk",
    location: "Fremont, CA",
    state: "CA",
    lat: 37.5485,
    lng: -121.9886,
    stage: "Series C",
    founded: 2016,
    fundingStage: "Series C",
    totalRaised: "$500M+",
    valuation: "$5B+",
    investors: ["Founders Fund", "Vy Capital"],
    tags: ["BCI", "brain interface", "Blindsight"],
    rosArticle: "The Neuralink Mafia, Brain Power, Rational Optimist Awards",
    rosCoverage: "Featured article"
  },
  {
    name: "Precision Neuroscience",
    sector: "Neurotech",
    description: "Founded by brain surgeon who helped build Neuralink. Layer 7 cortical interface — size of postage stamp, thinner than human hair.",
    thesis: "Less invasive brain interfaces enable faster adoption.",
    founder: "Benjamin Rapoport",
    location: "New York, NY",
    state: "NY",
    lat: 40.7128,
    lng: -74.0060,
    stage: "Series B",
    founded: 2021,
    fundingStage: "Series B",
    totalRaised: "$100M+",
    valuation: "",
    investors: ["Foresite Capital"],
    tags: ["BCI", "brain interface", "minimally invasive"],
    rosArticle: "The Neuralink Mafia",
    rosCoverage: "Featured article"
  },
  {
    name: "ElevenLabs",
    sector: "AI & Technology",
    description: "AI voice cloning company. Created digital replica of ALS patient's pre-ALS voice using old recordings.",
    thesis: "AI voice synthesis restores communication for those who've lost it.",
    founder: "Piotr Dabkowski, Mati Staniszewski",
    location: "New York, NY",
    state: "NY",
    lat: 40.7128,
    lng: -74.0060,
    stage: "Series C",
    founded: 2022,
    fundingStage: "Series C",
    totalRaised: "$180M+",
    valuation: "$3B+",
    investors: ["a16z", "Sequoia"],
    tags: ["AI", "voice synthesis", "TTS"],
    rosArticle: "The Neuralink Mafia",
    rosCoverage: "Featured article"
  },
  {
    name: "Atom Bodies",
    sector: "Biotech & Health",
    description: "AI-powered prosthetic arms with 26 degrees of freedom in fingers. Using large language models to interpret wearers' wishes. Takes just 5 minutes to teach the arm.",
    thesis: "LLMs make prosthetics intuitive — the arm understands what you want.",
    founder: "Tyler Hayes",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7740,
    lng: -122.4200,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    investors: [],
    tags: ["prosthetics", "AI", "bionics", "LLM"],
    rosArticle: "Neuralink Mafia, Ridley America Recharged, Rational Optimist Awards",
    rosCoverage: "Site visit, featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LONGEVITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Altos Labs",
    sector: "Longevity",
    description: "Cell reprogramming/rejuvenation. Backed by Jeff Bezos. Top scientists pursuing cellular reprogramming.",
    thesis: "Yamanaka factors can reverse cellular aging.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Late Stage",
    founded: 2022,
    fundingStage: "Late Stage",
    totalRaised: "$3B+",
    valuation: "",
    investors: ["Jeff Bezos", "Yuri Milner"],
    tags: ["longevity", "reprogramming", "rejuvenation"],
    rosArticle: "Cracking the Methuselah Code",
    rosCoverage: "Featured article"
  },
  {
    name: "Retro Biosciences",
    sector: "Longevity",
    description: "Cellular rejuvenation. $180M from Sam Altman. Targeting 10 extra healthy years.",
    thesis: "Adding 10 healthy years to human lifespan is achievable within a decade.",
    founder: "Joe Betts-LaCroix",
    location: "Redwood City, CA",
    state: "CA",
    lat: 37.4852,
    lng: -122.2364,
    stage: "Series A",
    founded: 2021,
    fundingStage: "Series A",
    totalRaised: "$180M",
    valuation: "",
    investors: ["Sam Altman"],
    tags: ["longevity", "cellular rejuvenation"],
    rosArticle: "Cracking the Methuselah Code",
    rosCoverage: "Featured article"
  },
  {
    name: "New Limit",
    sector: "Longevity",
    description: "Transcription factor research. Co-founded by Brian Armstrong (Coinbase).",
    thesis: "Epigenetic reprogramming can reverse aging.",
    founder: "Brian Armstrong",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "$100M+",
    valuation: "",
    investors: ["Brian Armstrong"],
    tags: ["longevity", "epigenetics", "transcription factors"],
    rosArticle: "Cracking the Methuselah Code",
    rosCoverage: "Featured article"
  },
  {
    name: "Loyal",
    sector: "Longevity",
    description: "Longevity drugs for dogs. First FDA-approved anti-aging drug (for dogs). Pathway to human treatments.",
    thesis: "Dogs provide faster iteration cycles for longevity research.",
    founder: "Celine Halioua",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series B",
    founded: 2019,
    fundingStage: "Series B",
    totalRaised: "$125M+",
    valuation: "",
    investors: ["a16z", "Founders Fund"],
    tags: ["longevity", "dogs", "FDA approved"],
    rosArticle: "Cracking the Methuselah Code",
    rosCoverage: "Featured article"
  },
  {
    name: "Insilico Medicine",
    sector: "Longevity",
    description: "AI-driven drug discovery. Using generative AI to design novel drug candidates.",
    thesis: "AI dramatically accelerates drug discovery timelines.",
    founder: "Alex Zhavoronkov",
    location: "Hong Kong",
    state: "",
    lat: 22.3193,
    lng: 114.1694,
    stage: "Late Stage",
    founded: 2014,
    fundingStage: "Late Stage",
    totalRaised: "$400M+",
    valuation: "",
    investors: [],
    tags: ["AI", "drug discovery", "longevity"],
    rosArticle: "How Many Lives, Cracking the Methuselah Code",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DELIVERY & LOGISTICS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Zipline",
    sector: "Delivery & Logistics",
    description: "American drone delivery company. 70% of Rwanda's blood supply. Partnerships with Walmart, Chipotle. 120 million miles flown. New Platform 2 drones.",
    thesis: "Drones solve last-mile delivery for critical supplies.",
    founder: "Keller Rinaudo",
    location: "South San Francisco, CA",
    state: "CA",
    lat: 37.6547,
    lng: -122.4077,
    stage: "Series F",
    founded: 2014,
    fundingStage: "Series F",
    totalRaised: "$900M+",
    valuation: "$4.5B",
    investors: ["a16z", "Sequoia", "Google Ventures"],
    tags: ["drone delivery", "medical supplies", "Walmart", "Chipotle"],
    rosArticle: "Rational Optimist Awards 2026, Is This a Pipedream, Ridley America",
    rosCoverage: "Recognized as company that best embodied rational optimist mindset"
  },
  {
    name: "Pipedream Labs",
    sector: "Delivery & Logistics",
    description: "Austin startup building underground tunnels for 'Otter' robots. 100 mph delivery. First Austin pilot: 40 miles, 100+ portals. Items anywhere to anywhere in under 15 minutes for less than 25 cents.",
    thesis: "Underground autonomous delivery eliminates traffic and weather.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2020,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    investors: [],
    tags: ["underground delivery", "robots", "tunnels", "Otter"],
    rosArticle: "Is This a Pipedream",
    rosCoverage: "Featured article"
  },
  {
    name: "The Boring Company",
    sector: "Delivery & Logistics",
    description: "Elon Musk's tunneling company. Built miles of car tunnels under Las Vegas convention center in 18 months at fraction of typical cost. Uses Prufrock autonomous tunnel-boring robot. Reduced costs from $1B+ to $12-15M per mile.",
    thesis: "Fast, cheap tunneling transforms urban transportation.",
    founder: "Elon Musk",
    location: "Bastrop, TX",
    state: "TX",
    lat: 30.1105,
    lng: -97.3155,
    stage: "Late Stage",
    founded: 2016,
    fundingStage: "Late Stage",
    totalRaised: "$675M+",
    valuation: "$5.7B",
    investors: ["Sequoia", "8VC"],
    tags: ["tunneling", "Prufrock", "Las Vegas", "Loop"],
    rosArticle: "Rational Optimist Awards, Is This a Pipedream, Ridley America",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HOUSING & CONSTRUCTION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Cuby Technologies",
    sector: "Housing & Construction",
    description: "'Henry Ford of housing'. Mobile Micro-Factory (MMF) for homebuilding. 122 shipping containers snapped together to pump out 200 homes/year in 30 days.",
    thesis: "Factory-built housing solves the affordability crisis.",
    founder: "Aleksandr Gampel",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    investors: [],
    tags: ["housing", "factory-built", "mobile factory", "MMF"],
    rosArticle: "The American Dream Needs a Factory Reset, We Must Defeat BANANA",
    rosCoverage: "Podcast interview with COO Aleksandr Gampel"
  },
  {
    name: "ICON",
    sector: "Housing & Construction",
    description: "Building world's largest 3D-printed neighborhood outside Austin. Giant robot weighing nearly 5 tons squeezes out concrete layers.",
    thesis: "3D printing enables rapid, affordable home construction.",
    founder: "Jason Ballard",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series B",
    founded: 2017,
    fundingStage: "Series B",
    totalRaised: "$450M+",
    valuation: "",
    investors: ["Tiger Global"],
    tags: ["3D printing", "construction", "housing"],
    rosArticle: "The New Air Force",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EDUCATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Alpha School",
    sector: "Education",
    description: "Austin-based. Founded by MacKenzie Price, backed by Joe Liemandt. Pioneered two-hour school day with AI tutor. 6/10 kids prefer school to vacation. Students test in top 1% in US; average SAT 1535/1600.",
    thesis: "If AI can personalize learning, we don't need 6-hour school days.",
    founder: "MacKenzie Price",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Early Stage",
    founded: 2019,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    investors: ["Joe Liemandt"],
    tags: ["education", "AI", "two-hour school day"],
    rosArticle: "Rational Optimist Awards, Why I'm Obsessed with AI Schooling",
    rosCoverage: "Site visit, featured article"
  },
  {
    name: "Synthesis",
    sector: "Education",
    description: "Interactive math tutor platform. Originated from Elon Musk's SpaceX school (Ad Astra). Game-based learning.",
    thesis: "Games are the most effective learning environment.",
    founder: "Josh Dahn, Chrisman Frank",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Series A",
    founded: 2020,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    investors: [],
    tags: ["education", "math", "gaming", "SpaceX school"],
    rosArticle: "Why I'm Obsessed with AI Schooling",
    rosCoverage: "Featured article"
  },
  {
    name: "Primer",
    sector: "Education",
    description: "Network of microschools with AI-integrated curriculum. Alternative education model.",
    thesis: "Small, technology-enhanced schools outperform large traditional ones.",
    founder: "Ryan Delk",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Series A",
    founded: 2022,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    investors: [],
    tags: ["education", "microschools", "AI"],
    rosArticle: "Why I'm Obsessed with AI Schooling",
    rosCoverage: "Featured article"
  },
  {
    name: "University of Austin",
    sector: "Education",
    description: "Startup university as alternative to traditional institutions. Focus on intellectual diversity and free inquiry.",
    thesis: "Higher education needs disruption from new institutions.",
    founder: "Pano Kanelos",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Nonprofit",
    founded: 2021,
    fundingStage: "Nonprofit",
    totalRaised: "$200M+",
    valuation: "",
    investors: [],
    tags: ["university", "higher education", "UATX"],
    rosArticle: "Austin + Detroit = Winning",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OCEAN TECH
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Ulysses",
    sector: "Ocean Tech",
    description: "Autonomous underwater drones planting seagrass. $1M first-year revenue. Contracts in Florida, Virginia, Western Australia. Ocean ecosystem restoration.",
    thesis: "Autonomous robots can restore ocean ecosystems at scale.",
    founder: "Will O'Brien",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    stage: "Seed",
    founded: 2022,
    fundingStage: "Seed",
    totalRaised: "$2M+",
    valuation: "",
    investors: [],
    tags: ["ocean tech", "seagrass", "ecosystem restoration", "underwater robots"],
    rosArticle: "Shady Stuff Underwater, SpaceX of the Sea",
    rosCoverage: "Featured article"
  },
  {
    name: "The Ocean Cleanup",
    sector: "Ocean Tech",
    description: "Ocean plastic removal organization. Rotterdam-based. System 002/03 interceptors. Removed millions of pounds of plastic.",
    thesis: "Technology can clean up ocean plastic pollution.",
    founder: "Boyan Slat",
    location: "Rotterdam, Netherlands",
    state: "",
    lat: 51.9244,
    lng: 4.4777,
    stage: "Nonprofit",
    founded: 2013,
    fundingStage: "Nonprofit",
    totalRaised: "$100M+",
    valuation: "",
    investors: [],
    tags: ["ocean cleanup", "plastic", "environmental"],
    rosArticle: "Weekly Diary",
    rosCoverage: "Featured article"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONSUMER TECH
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Osmo Labs",
    sector: "Consumer Tech",
    description: "First company to teleport a scent digitally. Built 'Generation' platform for custom AI-generated fragrances. Created 'Rational Optimist' scent on the spot at awards event.",
    thesis: "Digitizing smell unlocks applications from disease detection to food science.",
    founder: "Alex Wiltschko",
    location: "Cambridge, MA",
    state: "MA",
    lat: 42.3736,
    lng: -71.1097,
    stage: "Series B",
    founded: 2022,
    fundingStage: "Series B",
    totalRaised: "$100M+",
    valuation: "",
    investors: ["Google Ventures", "Lux Capital"],
    tags: ["AI", "olfaction", "scent", "fragrance", "digital smell"],
    rosArticle: "Rational Optimist Awards 2026, The First Nuclear SMR",
    rosCoverage: "Created custom ROS scent at awards event"
  },
  {
    name: "Tesla",
    sector: "Consumer Tech",
    description: "Full Self-Driving. Optimus humanoid robots. CyberTruck. Robotaxi service in Austin. 100X improvement in 2024.",
    thesis: "AI-powered autonomy transforms transportation and robotics.",
    founder: "Elon Musk",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    stage: "Public",
    founded: 2003,
    fundingStage: "Public",
    totalRaised: "",
    valuation: "Public",
    investors: [],
    tags: ["EV", "autonomy", "robotics", "Optimus", "FSD"],
    rosArticle: "Multiple articles",
    rosCoverage: "Referenced throughout"
  },
  {
    name: "Waymo",
    sector: "Consumer Tech",
    description: "Robotaxis clocked 100+ million fully autonomous miles. 1M+ rides monthly. 27% SF rideshare market.",
    thesis: "Autonomous vehicles will dominate urban transportation.",
    founder: "",
    location: "Mountain View, CA",
    state: "CA",
    lat: 37.3861,
    lng: -122.0839,
    stage: "Late Stage",
    founded: 2009,
    fundingStage: "Late Stage",
    totalRaised: "$5B+",
    valuation: "",
    investors: ["Alphabet"],
    tags: ["robotaxi", "autonomous vehicles", "rideshare"],
    rosArticle: "Rational Optimist Awards, Austin + Detroit, Going Robotic, Ridley America",
    rosCoverage: "Featured article"
  }
];

// Sector categories for filtering
const SECTORS = [
  "Defense & Security",
  "Nuclear Energy",
  "Fusion Energy",
  "Robotics & Manufacturing",
  "Supersonic & Hypersonic",
  "Space & Aerospace",
  "Climate & Energy",
  "AI & Technology",
  "Semiconductors",
  "Neurotech",
  "Biotech & Health",
  "Longevity",
  "Delivery & Logistics",
  "Housing & Construction",
  "Education",
  "Ocean Tech",
  "Consumer Tech"
];

// Funding stages for filtering
const STAGES = [
  "Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series D",
  "Series E",
  "Series F",
  "Late Stage",
  "Early Stage",
  "Public",
  "Acquired",
  "Bootstrapped",
  "Nonprofit"
];
